window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="\n        var hit = ev.target.closest(\"[data-rc-port], [data-rc-drop]"
window.__LT_RC_SRC+=", .rc-unit-stage, #rc-tray\");\n        if (!hit) {\n          setStatu"
window.__LT_RC_SRC+="s(\"Still armed. Tap a port or the outdoor unit.\", true);\n          r"
window.__LT_RC_SRC+="eturn;\n        }\n        applyDrop(armed, ev.clientX, ev.clientY);\n "
window.__LT_RC_SRC+="       armed = null;\n      },\n      true\n    );\n  }\n\n  function hose"
window.__LT_RC_SRC+="Img(btn, color, label) {\n    if (!btn) return;\n    var img = btn.que"
window.__LT_RC_SRC+="rySelector(\"img\");\n    if (img) img.src = hoseDataUri(color, label);"
window.__LT_RC_SRC+="\n  }\n\n  function build() {\n    var root = document.getElementById(\"r"
window.__LT_RC_SRC+="ecovery-root\");\n    if (!root) return;\n    ensureCss();\n    root.inn"
window.__LT_RC_SRC+="erHTML =\n      '<div class=\"rc-wrap\">' +\n      '<div class=\"rc-head\""
window.__LT_RC_SRC+="><h2>Recovery room</h2><button id=\"rc-reset\" class=\"btn\" type=\"butto"
window.__LT_RC_SRC+="n\">Reset bay</button></div>' +\n      '<p class=\"rc-lede\">Blue low ho"
window.__LT_RC_SRC+="se on LO. Red high hose on HI. Wrong port is one shop line. Scale is"
window.__LT_RC_SRC+=" the proof. 80% WC is a stop. Vacuum is a separate tool.</p>' +\n    "
window.__LT_RC_SRC+="  '<div id=\"rc-guide\" class=\"rc-guide\"><p id=\"rc-guide-say\" class=\"r"
window.__LT_RC_SRC+="c-guide-say\"></p>' +\n      '<div class=\"rc-guide-bar\"><button id=\"rc"
window.__LT_RC_SRC+="-skip-guide\" class=\"btn\" type=\"button\">Skip guide</button>' +\n      "
window.__LT_RC_SRC+="'<button id=\"rc-walk\" class=\"btn\" type=\"button\" hidden>Walk it again"
window.__LT_RC_SRC+="</button>' +\n      '<button id=\"rc-hub\" class=\"btn\" type=\"button\">As"
window.__LT_RC_SRC+="k HUB</button></div></div>' +\n      '<div class=\"rc-layout\"><div cla"
window.__LT_RC_SRC+="ss=\"rc-tray-col\" data-rc-drop=\"tray\"><p class=\"rc-label\">Parts left<"
window.__LT_RC_SRC+="/p><div id=\"rc-tray\"></div>' +\n      '<div class=\"rc-hose-row\">' +\n "
window.__LT_RC_SRC+="     '<button type=\"button\" id=\"rc-hose-vapor\" class=\"rc-hose rc-hos"
window.__LT_RC_SRC+="e-blue\" data-rc-hose=\"vapor\"><img alt=\"\" draggable=\"false\" /><span c"
window.__LT_RC_SRC+="lass=\"rc-hose-cap\">Blue low</span></button>' +\n      '<button type=\""
window.__LT_RC_SRC+="button\" id=\"rc-hose-liquid\" class=\"rc-hose rc-hose-red\" data-rc-hose"
window.__LT_RC_SRC+="=\"liquid\"><img alt=\"\" draggable=\"false\" /><span class=\"rc-hose-cap\">"
window.__LT_RC_SRC+="Red high</span></button>' +\n      '<button type=\"button\" id=\"rc-hose"
window.__LT_RC_SRC+="-vac\" class=\"rc-hose rc-hose-yellow\" data-rc-hose=\"vac\" hidden><img "
window.__LT_RC_SRC+="alt=\"\" draggable=\"false\" /><span class=\"rc-hose-cap\">Yellow vac</spa"
window.__LT_RC_SRC+="n></button>' +\n      '</div></div>' +\n      '<div class=\"rc-bay\"><p "
window.__LT_RC_SRC+="class=\"rc-label\">Outdoor unit</p>' +\n      '<div class=\"rc-unit-stag"
window.__LT_RC_SRC+="e\" id=\"rc-unit-stage\" data-rc-drop=\"bay\"><img class=\"rc-unit\" alt=\"O"
window.__LT_RC_SRC+="utdoor unit\" src=\"parts/condenser.png\" />' +\n      '<div class=\"rc-b"
window.__LT_RC_SRC+="ay-hooks\" id=\"rc-bay-hooks\"></div></div>' +\n      '<div class=\"rc-po"
window.__LT_RC_SRC+="rts\" style=\"display:flex;gap:8px;margin-top:6px\">' +\n      '<button "
window.__LT_RC_SRC+="type=\"button\" id=\"rc-port-lo\" class=\"rc-port rc-port-blue\" data-rc-p"
window.__LT_RC_SRC+="ort=\"lo\"><span>LO port</span></button>' +\n      '<button type=\"butto"
window.__LT_RC_SRC+="n\" id=\"rc-port-hi\" class=\"rc-port rc-port-red\" data-rc-port=\"hi\"><sp"
window.__LT_RC_SRC+="an>HI port</span></button>' +\n      '</div>' +\n      '<div class=\"rc"
window.__LT_RC_SRC+="-readout\"><div class=\"panel rc-manifold-lo\">LO <span id=\"rc-plow\">16"
window.__LT_RC_SRC+="2 psig</span><canvas id=\"rc-g-low\" width=\"120\" height=\"70\"></canvas>"
window.__LT_RC_SRC+="</div>' +\n      '<div class=\"panel rc-manifold-hi\">HI <span id=\"rc-p"
window.__LT_RC_SRC+="high\">442 psig</span><canvas id=\"rc-g-high\" width=\"120\" height=\"70\">"
window.__LT_RC_SRC+="</canvas></div></div>' +\n      '<div class=\"panel\" id=\"rc-scale-read"
window.__LT_RC_SRC+="\">0.0 lb on scale</div><div class=\"rc-scale-track\"><div id=\"rc-scale"
window.__LT_RC_SRC+="-bar\"></div></div>' +\n      '<div class=\"panel rc-micron\" id=\"rc-mic"
window.__LT_RC_SRC+="ron-panel\" hidden>Micron <span id=\"rc-micron-read\"></span></div>' +\n"
window.__LT_RC_SRC+="      '<div class=\"rc-switches\"><button type=\"button\" id=\"rc-machine"
window.__LT_RC_SRC+="-sw\" class=\"btn\">Recovery machine OFF</button>' +\n      '<button typ"
window.__LT_RC_SRC+="e=\"button\" id=\"rc-vacuum-sw\" class=\"btn\">Vacuum pump OFF</button></d"
window.__LT_RC_SRC+="iv>' +\n      '<p id=\"rc-status\" class=\"rc-status\"></p></div></div></"
window.__LT_RC_SRC+="div>';\n    hoseImg(document.getElementById(\"rc-hose-vapor\"), \"#2563e"
window.__LT_RC_SRC+="b\", \"LO\");\n    hoseImg(document.getElementById(\"rc-hose-liquid\"), \"#"
window.__LT_RC_SRC+="ef4444\", \"HI\");\n    hoseImg(document.getElementById(\"rc-hose-vac\"), "
window.__LT_RC_SRC+="\"#eab308\", \"VAC\");\n    bindDrag(root);\n    var msw = document.getEle"
window.__LT_RC_SRC+="mentById(\"rc-machine-sw\");\n    var vsw = document.getElementById(\"rc"
window.__LT_RC_SRC+="-vacuum-sw\");\n    if (msw) msw.addEventListener(\"click\", function ()"
window.__LT_RC_SRC+=" {\n      if (state.machine !== \"bay\") { shopWhy(\"Seat the recovery m"
window.__LT_RC_SRC+="achine on the outdoor unit first.\"); return; }\n      if (!state.vapo"
window.__LT_RC_SRC+="rHose || !state.liquidHose) { shopWhy(\"Land blue on LO and red on HI"
window.__LT_RC_SRC+=" before you flip the machine.\"); return; }\n      if (state.scale !=="
window.__LT_RC_SRC+=" \"bay\" || state.tank !== \"bay\") { shopWhy(\"Scale first. Tank on the "
window.__LT_RC_SRC+="scale. Scale is the proof.\"); return; }\n      state.machineOn = !sta"
window.__LT_RC_SRC+="te.machineOn;\n      if (state.machineOn) state.vacuumOn = false;\n   "
window.__LT_RC_SRC+="   paintTrayBay();\n      narrate();\n    });\n    if (vsw) vsw.addEven"
window.__LT_RC_SRC+="tListener(\"click\", function () {\n      if (!vacuumPhase()) { shopWhy"
window.__LT_RC_SRC+="(\"Vacuum is after recovery. 80% stop, machine back in the tray, then"
window.__LT_RC_SRC+=" yellow hose.\"); return; }\n      if (state.vacuum !== \"bay\") { shopW"
window.__LT_RC_SRC+="hy(\"Seat the vacuum pump on the unit first.\"); return; }\n      state"
window.__LT_RC_SRC+=".vacuumOn = !state.vacuumOn;\n      if (state.vacuumOn) state.machine"
window.__LT_RC_SRC+="On = false;\n      paintMicron();\n      paintTrayBay();\n      narrate"
window.__LT_RC_SRC+="();\n    });\n    document.getElementById(\"rc-reset\").addEventListener"
window.__LT_RC_SRC+="(\"click\", function () {\n      state = fresh();\n      guideStep = 0;\n"
window.__LT_RC_SRC+="      build();\n      narrate();\n    });\n    var skip = document.getE"
window.__LT_RC_SRC+="lementById(\"rc-skip-guide\");\n    if (skip) skip.addEventListener(\"cl"
window.__LT_RC_SRC+="ick\", function () { guideOn = false; paintGuide(); narrate(); });\n  "
window.__LT_RC_SRC+="  var walk = document.getElementById(\"rc-walk\");\n    if (walk) walk."
window.__LT_RC_SRC+="addEventListener(\"click\", function () { guideOn = true; guideStep = "
window.__LT_RC_SRC+="0; paintGuide(); });\n    var hub = document.getElementById(\"rc-hub\")"
window.__LT_RC_SRC+=";\n    if (hub) hub.addEventListener(\"click\", function () { narrate()"
window.__LT_RC_SRC+="; });\n    paintTrayBay();\n    paintGauges();\n    paintScale();\n    n"
window.__LT_RC_SRC+="arrate();\n    if (tick) clearInterval(tick);\n    tick = setInterval("
window.__LT_RC_SRC+="stepRecover, 700);\n  }\n\n  function openRecovery() {\n    if (!state) "
window.__LT_RC_SRC+="state = fresh();\n    try { if (localStorage.getItem(GUIDE_KEY) === \""
window.__LT_RC_SRC+="1\") guideOn = false; } catch (e) {}\n    build();\n  }\n\n  window.LT_op"
window.__LT_RC_SRC+="enRecovery = openRecovery;\n  var scr = document.getElementById(\"scre"
window.__LT_RC_SRC+="en-recovery\");\n  if (scr && (scr.classList.contains(\"active\") || scr"
window.__LT_RC_SRC+=".classList.contains(\"screen-on\"))) openRecovery();\n  if (window.Muta"
window.__LT_RC_SRC+="tionObserver && scr) {\n    new MutationObserver(function () {\n      "
window.__LT_RC_SRC+="if (scr.classList.contains(\"active\") || scr.classList.contains(\"scre"
window.__LT_RC_SRC+="en-on\")) {\n        if (!document.getElementById(\"rc-tray\")) openReco"
window.__LT_RC_SRC+="very();\n      }\n    }).observe(scr, { attributes: true, attributeFil"
window.__LT_RC_SRC+="ter: [\"class\", \"style\"] });\n  }\n})();\n"
