window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="     if (key === \"tank\" && state.scale !== \"bay\") {\n        "
window.__LT_RC_SRC+="shopWhy(\"Scale first — tank sits on the scale. Scale is the "
window.__LT_RC_SRC+="proof.\");\n        return;\n      }\n      if (key === \"vacuum\""
window.__LT_RC_SRC+=" && state.systemLeft > 0.5 && !atStop() && state.recovered <"
window.__LT_RC_SRC+=" 0.1) {\n        shopWhy(\"Vacuum pump comes AFTER recovery. S"
window.__LT_RC_SRC+="eat the recovery machine first.\");\n      }\n    }\n    if (des"
window.__LT_RC_SRC+="t === \"tray\" && key === \"machine\" && state.machineOn) {\n    "
window.__LT_RC_SRC+="  state.machineOn = false;\n    }\n    state[key] = dest;\n    "
window.__LT_RC_SRC+="if (state.machine !== \"bay\") state.machineOn = false;\n    if"
window.__LT_RC_SRC+=" (state.vacuum !== \"bay\") state.vacuumOn = false;\n    if (ke"
window.__LT_RC_SRC+="y === \"hoses\" && dest === \"tray\") {\n\n    }\n    paintTrayBay("
window.__LT_RC_SRC+=");\n    paintScale();\n    narrate();\n  }\n\n  function connectH"
window.__LT_RC_SRC+="ose(which) {\n    if (which === \"vapor\") {\n      state.vaporH"
window.__LT_RC_SRC+="ose = true;\n      if (state.hoses === \"tray\") state.hoses = "
window.__LT_RC_SRC+="\"bay\";\n    }\n    if (which === \"liquid\") {\n      state.liqui"
window.__LT_RC_SRC+="dHose = true;\n      if (state.hoses === \"tray\") state.hoses "
window.__LT_RC_SRC+="= \"bay\";\n    }\n    if (which === \"vac\") {\n      if (!vacuumP"
window.__LT_RC_SRC+="hase()) {\n        shopWhy(\"Yellow vacuum hose is for the vac"
window.__LT_RC_SRC+="uum step — finish recovery first.\");\n        return;\n      }"
window.__LT_RC_SRC+="\n      state.vacHose = true;\n    }\n    paintTrayBay();\n    n"
window.__LT_RC_SRC+="arrate();\n  }\n\n  function wrongHose(raw, port) {\n    if (raw"
window.__LT_RC_SRC+=".id === \"vapor\" && port === \"hi\") shopWhy(\"Wrong port — blue"
window.__LT_RC_SRC+=" low hose lands on LO, not HI.\");\n    else if (raw.id === \"l"
window.__LT_RC_SRC+="iquid\" && port === \"lo\") shopWhy(\"Wrong port "
