window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+=",\n    { id: \"scale\", key: \"scale\", label: \"Scale\", img: \"par"
window.__LT_RC_SRC+="ts/dmm.png\", bay: \"parts/dmm.png\" },\n    { id: \"gauges\", key"
window.__LT_RC_SRC+=": \"gauges\", label: \"Gauges\", img: \"parts/gauges.png\", bay: \""
window.__LT_RC_SRC+="parts/gauges.png\" },\n    { id: \"vacuum\", key: \"vacuum\", labe"
window.__LT_RC_SRC+="l: \"Vacuum pump\", img: \"parts/fanmotor.png\", bay: \"parts/fan"
window.__LT_RC_SRC+="motor.png\" },\n    { id: \"hoses\", key: \"hoses\", label: \"Hoses"
window.__LT_RC_SRC+="\", img: \"parts/gauges.png\", bay: \"parts/gauges.png\" },\n    {"
window.__LT_RC_SRC+=" id: \"ice\", key: \"ice\", label: \"Ice bucket\", img: \"parts/acc"
window.__LT_RC_SRC+="umulator.png\", bay: \"parts/accumulator.png\", optional: true "
window.__LT_RC_SRC+="}\n  ];\n\n  var GUIDE = [\n    { say: \"Professor HUB: Drag the "
window.__LT_RC_SRC+="machine photo onto the outdoor unit.\", need: \"machineBay\", h"
window.__LT_RC_SRC+="ighlight: \"[data-rc-part='machine']\" },\n    { say: \"Professo"
window.__LT_RC_SRC+="r HUB: Drag the tank onto the scale — scale is the proof.\", "
window.__LT_RC_SRC+="need: \"tankOnScale\", highlight: \"[data-rc-part='tank'],[data"
window.__LT_RC_SRC+="-rc-part='scale']\" },\n    { say: \"Professor HUB: Drag the bl"
window.__LT_RC_SRC+="ue low hose onto LO, then the red high hose onto HI.\", need:"
window.__LT_RC_SRC+=" \"hosesLanded\", highlight: \"[data-rc-hose],[data-rc-port]\" }"
window.__LT_RC_SRC+=",\n    { say: \"Professor HUB: Turn the machine ON. Watch the "
window.__LT_RC_SRC+="gauges drop and the scale climb.\", need: \"machineRunning\", h"
window.__LT_RC_SRC+="ighlight: \"#rc-machine-sw\" },\n    { say: \"Professor HUB: Sto"
window.__LT_RC_SRC+="p at 80% of water capacity. 80% is a stop, not a goal.\", nee"
window.__LT_RC_SRC+="d: \"hitStop\", highlight: \"#rc-scale-read\" },\n    { say: \"Pro"
window.__LT_RC_SRC+="fessor HUB: Put the machine back in the tray. Vacuum pump is"
window.__LT_RC_SRC+=" the next tool — separate.\", need: \"machineBa"
