window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="     if (capturing && capturing.releasePointerCapture) captu"
window.__LT_RC_SRC+="ring.releasePointerCapture(start.pointerId);\n      } catch ("
window.__LT_RC_SRC+="e) {}\n      capturing = null;\n      clearGhost();\n      if ("
window.__LT_RC_SRC+="!start.moved) {\n        /* click-to-seat arm */\n        arme"
window.__LT_RC_SRC+="d = { kind: start.kind, id: start.id };\n        setStatus(\n "
window.__LT_RC_SRC+="         start.kind === \"hose\"\n            ? \"Armed \" + (sta"
window.__LT_RC_SRC+="rt.id === \"vapor\" ? \"blue low hose\" : start.id === \"liquid\" "
window.__LT_RC_SRC+="? \"red high hose\" : \"yellow vacuum hose\") + \" — tap LO or HI"
window.__LT_RC_SRC+=" port.\"\n            : \"Armed \" + start.id + \" — tap the outd"
window.__LT_RC_SRC+="oor unit (or tray) to seat it.\",\n          false\n        );\n"
window.__LT_RC_SRC+="        return;\n      }\n      applyDrop({ kind: start.kind, "
window.__LT_RC_SRC+="id: start.id }, ev.clientX, ev.clientY);\n      drag = null;\n"
window.__LT_RC_SRC+="      /* swallow the synthetic click after a real drag */\n  "
window.__LT_RC_SRC+="    var kill = function (e) {\n        e.preventDefault();\n  "
window.__LT_RC_SRC+="      e.stopPropagation();\n        document.removeEventListe"
window.__LT_RC_SRC+="ner(\"click\", kill, true);\n      };\n      document.addEventLi"
window.__LT_RC_SRC+="stener(\"click\", kill, true);\n      setTimeout(function () {\n"
window.__LT_RC_SRC+="        document.removeEventListener(\"click\", kill, true);\n "
window.__LT_RC_SRC+="     }, 350);\n    }\n\n    root.addEventListener(\"pointerup\", "
window.__LT_RC_SRC+="endPtr, true);\n    root.addEventListener(\"pointercancel\", en"
window.__LT_RC_SRC+="dPtr, true);\n\n    root.addEventListener(\n      \"click\",\n    "
window.__LT_RC_SRC+="  function (ev) {\n        if (ev.target.closest(\"#rc-machine"
window.__LT_RC_SRC+="-sw,#rc-vacuum-sw,#rc-reset,#rc-hub,#rc-walk,#rc-skip-guide\""
window.__LT_RC_SRC+=")) return;\n        if (!armed) return;\n      "