window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="r.width / 2, cy = r.top + r.height / 2;\n          var d = (x"
window.__LT_RC_SRC+=" - cx) * (x - cx) + (y - cy) * (y - cy);\n          if (d < b"
window.__LT_RC_SRC+="estD) { bestD = d; best = ports[j]; }\n        }\n      }\n    "
window.__LT_RC_SRC+="  if (best) port = best;\n    }\n    return { port: port, zone"
window.__LT_RC_SRC+=": zone, scale: scale, unit: unit };\n  }\n\n  function applyDro"
window.__LT_RC_SRC+="p(payload, x, y) {\n    if (!payload) return;\n    var hit = h"
window.__LT_RC_SRC+="itDrop(x, y);\n    if (payload.kind === \"hose\") {\n      if (h"
window.__LT_RC_SRC+="it.port) {\n        var p = hit.port.getAttribute(\"data-rc-po"
window.__LT_RC_SRC+="rt\");\n        if (payload.id === \"vapor\" && p === \"lo\") conn"
window.__LT_RC_SRC+="ectHose(\"vapor\");\n        else if (payload.id === \"liquid\" &"
window.__LT_RC_SRC+="& p === \"hi\") connectHose(\"liquid\");\n        else if (payloa"
window.__LT_RC_SRC+="d.id === \"vac\" && (p === \"lo\" || p === \"hi\" || p === \"vac\"))"
window.__LT_RC_SRC+=" connectHose(\"vac\");\n        else wrongHose(payload, p);\n   "
window.__LT_RC_SRC+="     return;\n      }\n      if (hit.zone && hit.zone.getAttri"
window.__LT_RC_SRC+="bute(\"data-rc-drop\") === \"bay\") {\n        shopWhy(\"Drop the "
window.__LT_RC_SRC+="hose on a port — blue LO, red HI\" + (vacuumPhase() ? \", yell"
window.__LT_RC_SRC+="ow for vacuum.\" : \".\"));\n      } else {\n        shopWhy(\"Hos"
window.__LT_RC_SRC+="es land on the outdoor unit ports, not the tray.\");\n      }\n"
window.__LT_RC_SRC+="      return;\n    }\n    if (payload.kind === \"part\") {\n     "
window.__LT_RC_SRC+=" if (hit.zone) {\n        var dest = hit.zone.getAttribute(\"d"
window.__LT_RC_SRC+="ata-rc-drop\");\n        if (dest === \"bay\" || dest === \"tray\""
window.__LT_RC_SRC+=") {\n          if (payload.id === \"tank\" && dest === \"bay\" &&"
window.__LT_RC_SRC+=" hit.scale && state.scale !== \"bay\") {\n            shopWhy(\""
window.__LT_RC_SRC+="Scale first — tank sits on the scale. Scale i"
