window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="ck\", highlight: \"[data-rc-part='machine']\" }\n  ];\n\n  functio"
window.__LT_RC_SRC+="n asset(path) {\n    return path + \"?v=\" + ASSET_V;\n  }\n\n  fu"
window.__LT_RC_SRC+="nction fresh() {\n    return {\n      machine: \"tray\",\n      v"
window.__LT_RC_SRC+="acuum: \"tray\",\n      scale: \"tray\",\n      tank: \"tray\",\n    "
window.__LT_RC_SRC+="  gauges: \"tray\",\n      hoses: \"tray\",\n      ice: \"tray\",\n  "
window.__LT_RC_SRC+="    vaporHose: false,\n      liquidHose: false,\n      vacHose"
window.__LT_RC_SRC+=": false,\n      machineOn: false,\n      vacuumOn: false,\n    "
window.__LT_RC_SRC+="  microns: 760000,\n      recovered: 0,\n      systemLeft: SYS"
window.__LT_RC_SRC+="_CHARGE,\n      pLow: 162,\n      pHigh: 442,\n      finishedOn"
window.__LT_RC_SRC+="ce: false\n    };\n  }\n\n  function pct() {\n    return Math.min"
window.__LT_RC_SRC+="(100, Math.round((state.recovered / WC_LB) * 1000) / 10);\n  "
window.__LT_RC_SRC+="}\n  function atStop() {\n    return pct() >= STOP_PCT;\n  }\n  "
window.__LT_RC_SRC+="function canRecover() {\n    return (\n      state.machine ==="
window.__LT_RC_SRC+=" \"bay\" &&\n      state.tank === \"bay\" &&\n      state.scale =="
window.__LT_RC_SRC+="= \"bay\" &&\n      state.vaporHose &&\n      state.liquidHose &"
window.__LT_RC_SRC+="&\n      state.machineOn &&\n      !atStop() &&\n      state.sy"
window.__LT_RC_SRC+="stemLeft > 0.05\n    );\n  }\n\n  function el(tag, cls, html) {\n"
window.__LT_RC_SRC+="    var n = document.createElement(tag);\n    if (cls) n.clas"
window.__LT_RC_SRC+="sName = cls;\n    if (html != null) n.innerHTML = html;\n    r"
window.__LT_RC_SRC+="eturn n;\n  }\n\n  function ensureCss() {\n    if (document.getE"
window.__LT_RC_SRC+="lementById(\"rc-photo-css\")) return;\n    var s = document.cre"
window.__LT_RC_SRC+="ateElement(\"link\");\n    s.id = \"rc-photo-css\";\n    s.rel = \""
window.__LT_RC_SRC+="stylesheet\";\n    s.href = \"recovery-room.css?v=\" + ASSET_V;\n"
window.__LT_RC_SRC+="    document.head.appendChild(s);\n  }\n\n  func"
