window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="    state.microns = 760000;\n    }\n    var m = Math.round(sta"
window.__LT_RC_SRC+="te.microns);\n    read.textContent = m >= 1000 ? Math.round(m"
window.__LT_RC_SRC+=" / 1000) + \"k microns\" : m + \" microns\";\n  }\n\n  function pai"
window.__LT_RC_SRC+="ntScale() {\n    var sc = document.getElementById(\"rc-scale-r"
window.__LT_RC_SRC+="ead\");\n    if (!sc) return;\n    var p = pct();\n    sc.textCo"
window.__LT_RC_SRC+="ntent =\n      state.recovered.toFixed(1) + \" lb on scale · \""
window.__LT_RC_SRC+=" + p.toFixed(1) + \"% of \" + WC_LB + \" lb WC\";\n    sc.classLi"
window.__LT_RC_SRC+="st.toggle(\"rc-stop\", p >= STOP_PCT);\n    var bar = document."
window.__LT_RC_SRC+="getElementById(\"rc-scale-bar\");\n    if (bar) {\n      bar.sty"
window.__LT_RC_SRC+="le.width = Math.min(100, p) + \"%\";\n      bar.style.backgroun"
window.__LT_RC_SRC+="d = p >= STOP_PCT ? \"#ef4444\" : p >= 70 ? \"#f59e0b\" : \"#22c5"
window.__LT_RC_SRC+="5e\";\n    }\n  }\n\n  function makeChip(it) {\n    var b = el(\"bu"
window.__LT_RC_SRC+="tton\", \"rc-chip\");\n    b.type = \"button\";\n    b.setAttribute"
window.__LT_RC_SRC+="(\"data-rc-part\", it.id);\n    b.draggable = true;\n    b.title"
window.__LT_RC_SRC+=" = it.label + (it.optional ? \" (optional)\" : \"\");\n    var im"
window.__LT_RC_SRC+="g = document.createElement(\"img\");\n    img.src = asset(it.im"
window.__LT_RC_SRC+="g);\n    img.alt = it.label;\n    img.draggable = false;\n    b"
window.__LT_RC_SRC+=".appendChild(img);\n    b.appendChild(el(\"span\", null, it.lab"
window.__LT_RC_SRC+="el));\n    return b;\n  }\n\n  function paintTrayBay() {\n    var"
window.__LT_RC_SRC+=" tray = document.getElementById(\"rc-tray\");\n    var hooks = "
window.__LT_RC_SRC+="document.getElementById(\"rc-bay-hooks\");\n    if (!tray || !h"
window.__LT_RC_SRC+="ooks) return;\n    tray.innerHTML = \"\";\n    hooks.innerHTML ="
window.__LT_RC_SRC+=" \"\";\n    PARTS.forEach(function (it) {\n      var where = sta"
window.__LT_RC_SRC+="te[it.key];\n      if (where === \"tray\") {\n   "
