window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="text/lt-rc\", JSON.stringify(drag));\n        ev.dataTransfer."
window.__LT_RC_SRC+="setData(\"text/plain\", drag.kind + \":\" + drag.id);\n        ev"
window.__LT_RC_SRC+=".dataTransfer.effectAllowed = \"move\";\n        var img = t.qu"
window.__LT_RC_SRC+="erySelector(\"img\");\n        if (img && ev.dataTransfer.setDr"
window.__LT_RC_SRC+="agImage) {\n          ev.dataTransfer.setDragImage(img, img.w"
window.__LT_RC_SRC+="idth / 2 || 40, img.height / 2 || 40);\n        }\n      } cat"
window.__LT_RC_SRC+="ch (e) {}\n    });\n    root.addEventListener(\"dragover\", func"
window.__LT_RC_SRC+="tion (ev) {\n      ev.preventDefault();\n      var stage = ev."
window.__LT_RC_SRC+="target.closest(\".rc-unit-stage\");\n      if (stage) stage.cla"
window.__LT_RC_SRC+="ssList.add(\"rc-over\");\n    });\n    root.addEventListener(\"dr"
window.__LT_RC_SRC+="agleave\", function (ev) {\n      var stage = ev.target.closes"
window.__LT_RC_SRC+="t(\".rc-unit-stage\");\n      if (stage) stage.classList.remove"
window.__LT_RC_SRC+="(\"rc-over\");\n    });\n    root.addEventListener(\"drop\", funct"
window.__LT_RC_SRC+="ion (ev) {\n      ev.preventDefault();\n      document.querySe"
window.__LT_RC_SRC+="lectorAll(\".rc-over\").forEach(function (n) {\n        n.class"
window.__LT_RC_SRC+="List.remove(\"rc-over\");\n      });\n      var raw = null;\n    "
window.__LT_RC_SRC+="  try {\n        raw = JSON.parse(ev.dataTransfer.getData(\"te"
window.__LT_RC_SRC+="xt/lt-rc\") || \"null\");\n      } catch (e) {}\n      if (!raw) "
window.__LT_RC_SRC+="raw = drag;\n      drag = null;\n      if (!raw) return;\n     "
window.__LT_RC_SRC+=" applyDrop(raw, ev.clientX, ev.clientY);\n    });\n\n    root.a"
window.__LT_RC_SRC+="ddEventListener(\n      \"pointerdown\",\n      function (ev) {\n"
window.__LT_RC_SRC+="        var t = ev.target.closest(\"[data-rc-part], [data-rc-"
window.__LT_RC_SRC+="hose]\");\n        if (!t || ev.button) return;\n        if (ev"
window.__LT_RC_SRC+=".target.closest(\"#rc-machine-sw,#rc-vacuum-sw"