window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="     tray.appendChild(makeChip(it));\n      } else {\n        "
window.__LT_RC_SRC+="var hook = el(\"div\", \"rc-hook\");\n        hook.setAttribute(\""
window.__LT_RC_SRC+="data-hook\", it.id);\n        hook.setAttribute(\"data-rc-part\""
window.__LT_RC_SRC+=", it.id);\n        hook.draggable = true;\n        var img = d"
window.__LT_RC_SRC+="ocument.createElement(\"img\");\n        img.src = asset(it.bay"
window.__LT_RC_SRC+=");\n        img.alt = it.label + \" hooked up\";\n        img.dr"
window.__LT_RC_SRC+="aggable = false;\n        hook.appendChild(img);\n        hook"
window.__LT_RC_SRC+="s.appendChild(hook);\n      }\n    });\n\n    var lo = document."
window.__LT_RC_SRC+="getElementById(\"rc-port-lo\");\n    var hi = document.getEleme"
window.__LT_RC_SRC+="ntById(\"rc-port-hi\");\n    if (lo) lo.classList.toggle(\"rc-on"
window.__LT_RC_SRC+="\", state.vaporHose);\n    if (hi) hi.classList.toggle(\"rc-on\""
window.__LT_RC_SRC+=", state.liquidHose);\n\n    var hv = document.getElementById(\""
window.__LT_RC_SRC+="rc-hose-vapor\");\n    var hl = document.getElementById(\"rc-ho"
window.__LT_RC_SRC+="se-liquid\");\n    var hy = document.getElementById(\"rc-hose-v"
window.__LT_RC_SRC+="ac\");\n    function markHose(btn, landed, idleLabel, landLabe"
window.__LT_RC_SRC+="l) {\n      if (!btn) return;\n      btn.classList.toggle(\"pri"
window.__LT_RC_SRC+="mary\", landed);\n      btn.classList.toggle(\"rc-hose-landed\","
window.__LT_RC_SRC+=" landed);\n      var cap = btn.querySelector(\".rc-hose-cap\");"
window.__LT_RC_SRC+="\n      if (cap) cap.textContent = landed ? landLabel : idleL"
window.__LT_RC_SRC+="abel;\n    }\n    markHose(hv, state.vaporHose, \"Blue low\", \"B"
window.__LT_RC_SRC+="lue · landed\");\n    markHose(hl, state.liquidHose, \"Red high"
window.__LT_RC_SRC+="\", \"Red · landed\");\n    markHose(hy, state.vacHose, \"Yellow "
window.__LT_RC_SRC+="vac\", \"Yellow · seated\");\n    if (hy) hy.hidden = !vacuumPha"
window.__LT_RC_SRC+="se();\n    if (lo) {\n      lo.classList.toggle"
