window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+=",#rc-reset,#rc-hub,#rc-walk,#rc-skip-guide\")) return;\n      "
window.__LT_RC_SRC+="  var part = t.getAttribute(\"data-rc-part\");\n        var hos"
window.__LT_RC_SRC+="e = t.getAttribute(\"data-rc-hose\");\n        ptr = {\n        "
window.__LT_RC_SRC+="  kind: part ? \"part\" : \"hose\",\n          id: part || hose,\n"
window.__LT_RC_SRC+="          x: ev.clientX,\n          y: ev.clientY,\n          "
window.__LT_RC_SRC+="moved: false,\n          captured: false,\n          el: t,\n  "
window.__LT_RC_SRC+="        pointerId: ev.pointerId\n        };\n      },\n      tr"
window.__LT_RC_SRC+="ue\n    );\n\n    root.addEventListener(\n      \"pointermove\",\n "
window.__LT_RC_SRC+="     function (ev) {\n        if (!ptr) return;\n        var d"
window.__LT_RC_SRC+="x = ev.clientX - ptr.x;\n        var dy = ev.clientY - ptr.y;"
window.__LT_RC_SRC+="\n        if (!ptr.captured) {\n          if (dx * dx + dy * d"
window.__LT_RC_SRC+="y < 64) return; /* 8px slop */\n          ptr.captured = true"
window.__LT_RC_SRC+=";\n          ptr.moved = true;\n          armed = null;\n      "
window.__LT_RC_SRC+="    try {\n            if (ptr.el && ptr.el.setPointerCapture"
window.__LT_RC_SRC+=") ptr.el.setPointerCapture(ptr.pointerId);\n          } catch"
window.__LT_RC_SRC+=" (e) {}\n          capturing = ptr.el;\n          showGhost(pt"
window.__LT_RC_SRC+="r.el, ev.clientX, ev.clientY);\n          if (ev.cancelable) "
window.__LT_RC_SRC+="ev.preventDefault();\n        } else {\n          if (ghost) {"
window.__LT_RC_SRC+="\n            ghost.style.left = ev.clientX - 32 + \"px\";\n    "
window.__LT_RC_SRC+="        ghost.style.top = ev.clientY - 32 + \"px\";\n          "
window.__LT_RC_SRC+="}\n          if (ev.cancelable) ev.preventDefault();\n        "
window.__LT_RC_SRC+="}\n      },\n      { capture: true, passive: false }\n    );\n\n "
window.__LT_RC_SRC+="   function endPtr(ev) {\n      if (!ptr) return;\n      var s"
window.__LT_RC_SRC+="tart = ptr;\n      ptr = null;\n      try {\n   "