window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+=" the tray. Vacuum pump is the next tool — dehydration, separ"
window.__LT_RC_SRC+="ate from recovery.\");\n      return;\n    }\n    if (state.vacu"
window.__LT_RC_SRC+="umOn && state.machineOn) {\n      shopWhy(\"Vacuum pump is for"
window.__LT_RC_SRC+=" dehydration AFTER the charge is out — kill recovery first.\""
window.__LT_RC_SRC+=");\n      return;\n    }\n    if (state.vacuumOn && state.syste"
window.__LT_RC_SRC+="mLeft > 0.5) {\n      shopWhy(\"Vacuum with charge still in th"
window.__LT_RC_SRC+="e box — wrong tool. Recover first.\");\n      return;\n    }\n  "
window.__LT_RC_SRC+="  if (canRecover()) {\n      setStatus(\"Recovering — gauges d"
window.__LT_RC_SRC+="rop, scale climbs. Proof is on the scale.\");\n      return;\n "
window.__LT_RC_SRC+="   }\n    if (state.machine !== \"bay\") {\n      setStatus(\"Dra"
window.__LT_RC_SRC+="g the recovery machine photo onto the outdoor unit.\");\n     "
window.__LT_RC_SRC+=" return;\n    }\n    if (state.scale !== \"bay\" || state.tank !"
window.__LT_RC_SRC+="== \"bay\") {\n      setStatus(\"Seat the scale, then park the t"
window.__LT_RC_SRC+="ank on it — scale is the proof.\");\n      return;\n    }\n    i"
window.__LT_RC_SRC+="f (!state.vaporHose || !state.liquidHose) {\n      setStatus("
window.__LT_RC_SRC+="\"Land low hose on LO, then high hose on HI.\");\n      return;"
window.__LT_RC_SRC+="\n    }\n    if (!state.machineOn) {\n      setStatus(\"Hoses an"
window.__LT_RC_SRC+="d bottle set. Flip Recovery machine ON. Vacuum stays OFF.\");"
window.__LT_RC_SRC+="\n      return;\n    }\n    if (state.systemLeft <= 0.05) {\n   "
window.__LT_RC_SRC+="   setStatus(\"System empty enough. Vacuum is the separate to"
window.__LT_RC_SRC+="ol now.\");\n      return;\n    }\n    setStatus(\"Recovery bay r"
window.__LT_RC_SRC+="eady.\");\n  }\n\n  function placePart(id, dest) {\n    var key ="
window.__LT_RC_SRC+=" id === \"cylinder\" ? \"tank\" : id;\n    if (!state.hasOwnPrope"
window.__LT_RC_SRC+="rty(key)) return;\n    if (dest === \"bay\") {\n "
