window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="— red high hose lands on HI, not LO.\");\n    else if (raw.id "
window.__LT_RC_SRC+="=== \"vac\") shopWhy(\"Wrong port — yellow vacuum hose seats af"
window.__LT_RC_SRC+="ter recovery, not mixed into the pull.\");\n    else shopWhy(\""
window.__LT_RC_SRC+="Wrong drop — blue → LO, red → HI.\");\n  }\n\n  function stepRec"
window.__LT_RC_SRC+="over() {\n    if (!canRecover()) {\n      if (state.machineOn "
window.__LT_RC_SRC+="&& atStop()) {\n        state.machineOn = false;\n        pain"
window.__LT_RC_SRC+="tTrayBay();\n        narrate();\n      }\n      if (vacuumPhase"
window.__LT_RC_SRC+="()) paintMicron();\n      return;\n    }\n    var bite = 0.12;\n"
window.__LT_RC_SRC+="    if (state.systemLeft < bite) bite = state.systemLeft;\n  "
window.__LT_RC_SRC+="  state.systemLeft -= bite;\n    state.recovered += bite;\n   "
window.__LT_RC_SRC+=" var done = 1 - state.systemLeft / SYS_CHARGE;\n    state.pLo"
window.__LT_RC_SRC+="w = Math.max(0, 162 * (1 - done * 0.98));\n    state.pHigh = "
window.__LT_RC_SRC+="Math.max(5, 442 * (1 - done * 0.95));\n    if (atStop()) {\n  "
window.__LT_RC_SRC+="    state.machineOn = false;\n      state.recovered = (STOP_P"
window.__LT_RC_SRC+="CT / 100) * WC_LB;\n    }\n    paintGauges();\n    paintScale()"
window.__LT_RC_SRC+=";\n    paintTrayBay();\n    narrate();\n  }\n\nfunction ensureGho"
window.__LT_RC_SRC+="st() {\n    var g = document.getElementById(\"rc-drag-ghost\");"
window.__LT_RC_SRC+="\n    if (g) return g;\n    g = document.createElement(\"div\");"
window.__LT_RC_SRC+="\n    g.id = \"rc-drag-ghost\";\n    g.setAttribute(\"aria-hidden"
window.__LT_RC_SRC+="\", \"true\");\n    g.style.cssText =\n      \"position:fixed;z-in"
window.__LT_RC_SRC+="dex:99999;pointer-events:none;display:none;\" +\n      \"width:"
window.__LT_RC_SRC+="64px;height:64px;border-radius:10px;border:2px solid #f59e0b"
window.__LT_RC_SRC+=";\" +\n      \"background:rgba(15,12,8,.92);box-shadow:0 8px 24"
window.__LT_RC_SRC+="px rgba(0,0,0,.45);\" +\n      \"align-items:cen"
