window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+=".fillStyle = color;\n    ctx.beginPath();\n    ctx.arc(cx, cy,"
window.__LT_RC_SRC+=" 3.5, 0, Math.PI * 2);\n    ctx.fill();\n    ctx.fillStyle = \""
window.__LT_RC_SRC+="#f4e7c8\";\n    ctx.font = \"700 9px system-ui,sans-serif\";\n   "
window.__LT_RC_SRC+=" ctx.textAlign = \"center\";\n    ctx.fillText(label, cx, cy + "
window.__LT_RC_SRC+="r + 2);\n  }\n\n  function paintGauges() {\n    var lo = documen"
window.__LT_RC_SRC+="t.getElementById(\"rc-plow\");\n    var hi = document.getElemen"
window.__LT_RC_SRC+="tById(\"rc-phigh\");\n    if (lo) lo.textContent = Math.round(s"
window.__LT_RC_SRC+="tate.pLow) + \" psig\";\n    if (hi) hi.textContent = Math.roun"
window.__LT_RC_SRC+="d(state.pHigh) + \" psig\";\n    drawNeedle(document.getElement"
window.__LT_RC_SRC+="ById(\"rc-g-low\"), state.pLow, 300, \"#3b82f6\", \"LO\");\n    dra"
window.__LT_RC_SRC+="wNeedle(document.getElementById(\"rc-g-high\"), state.pHigh, 5"
window.__LT_RC_SRC+="00, \"#ef4444\", \"HI\");\n    paintMicron();\n  }\n\n  function vac"
window.__LT_RC_SRC+="uumPhase() {\n    return atStop() && state.machine === \"tray\""
window.__LT_RC_SRC+=";\n  }\n\n  function paintMicron() {\n    var panel = document.g"
window.__LT_RC_SRC+="etElementById(\"rc-micron-panel\");\n    var read = document.ge"
window.__LT_RC_SRC+="tElementById(\"rc-micron-read\");\n    var hoseY = document.get"
window.__LT_RC_SRC+="ElementById(\"rc-hose-vac\");\n    if (panel) panel.hidden = !v"
window.__LT_RC_SRC+="acuumPhase();\n    if (hoseY) hoseY.hidden = !vacuumPhase();\n"
window.__LT_RC_SRC+="    if (!read) return;\n    if (!vacuumPhase()) {\n      read."
window.__LT_RC_SRC+="textContent = \"—\";\n      return;\n    }\n    if (state.vacuumO"
window.__LT_RC_SRC+="n && state.vacHose) {\n      state.microns = Math.max(250, st"
window.__LT_RC_SRC+="ate.microns * 0.92);\n    } else if (state.vacuum === \"bay\" &"
window.__LT_RC_SRC+="& state.vacHose) {\n      state.microns = Math.max(5000, Math"
window.__LT_RC_SRC+=".min(760000, state.microns));\n    } else {\n  "
