window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="/* Allstars — Recovery photo bench. Scale is the proof. 80% "
window.__LT_RC_SRC+="WC is a stop. Vacuum ≠ recovery. */\n(function () {\n  \"use st"
window.__LT_RC_SRC+="rict\";\n\n  var WC_LB = 10;\n  var STOP_PCT = 80;\n  var SYS_CHA"
window.__LT_RC_SRC+="RGE = 9.0;\n  var ASSET_V = \"5\";\n  var GUIDE_KEY = \"lt-rc-gui"
window.__LT_RC_SRC+="de-done-v1\";\n\n  var state = null;\n  var drag = null;\n  var t"
window.__LT_RC_SRC+="ick = null;\n  var guideOn = true;\n  var guideStep = 0;\n  var"
window.__LT_RC_SRC+=" ptr = null;\n\n\n  function hoseDataUri(color, label) {\n    va"
window.__LT_RC_SRC+="r c = color || \"#2563eb\";\n    var svg =\n      '<svg xmlns=\"h"
window.__LT_RC_SRC+="ttp://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\">' +\n      '<r"
window.__LT_RC_SRC+="ect width=\"64\" height=\"64\" rx=\"10\" fill=\"#efe6d6\"/>' +\n     "
window.__LT_RC_SRC+=" '<path d=\"M12 40c8-18 32-18 40 0\" fill=\"none\" stroke=\"' + c"
window.__LT_RC_SRC+=" + '\" stroke-width=\"10\" stroke-linecap=\"round\"/>' +\n      '<"
window.__LT_RC_SRC+="path d=\"M14 38c7-14 29-14 36 0\" fill=\"none\" stroke=\"#1a140c\""
window.__LT_RC_SRC+=" stroke-width=\"2\" opacity=\".25\"/>' +\n      '<circle cx=\"12\" "
window.__LT_RC_SRC+="cy=\"40\" r=\"5\" fill=\"#1a140c\"/><circle cx=\"52\" cy=\"40\" r=\"5\" "
window.__LT_RC_SRC+="fill=\"#1a140c\"/>' +\n      '<text x=\"32\" y=\"58\" text-anchor=\""
window.__LT_RC_SRC+="middle\" font-size=\"9\" font-family=\"system-ui,sans-serif\" fon"
window.__LT_RC_SRC+="t-weight=\"700\" fill=\"#1a140c\">' +\n      (label || \"\") +\n    "
window.__LT_RC_SRC+="  \"</text></svg>\";\n    return \"data:image/svg+xml,\" + encode"
window.__LT_RC_SRC+="URIComponent(svg);\n  }\n\n  var PARTS = [\n    { id: \"machine\","
window.__LT_RC_SRC+=" key: \"machine\", label: \"Recovery machine\", img: \"parts/comp"
window.__LT_RC_SRC+="ressor.png\", bay: \"parts/compressor.png\" },\n    { id: \"tank\""
window.__LT_RC_SRC+=", key: \"tank\", label: \"Recovery tank\", img: \"allstars/eq/cut"
window.__LT_RC_SRC+="/tank.jpg\", bay: \"allstars/eq/cut/tank.jpg\" }"
