window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="s the proof.\");\n            return;\n          }\n          pl"
window.__LT_RC_SRC+="acePart(payload.id, dest);\n          return;\n        }\n     "
window.__LT_RC_SRC+=" }\n      if (hit.unit || hit.scale) {\n        placePart(payl"
window.__LT_RC_SRC+="oad.id, \"bay\");\n        return;\n      }\n      shopWhy(\"Drop "
window.__LT_RC_SRC+="that photo on the outdoor unit bay — or back in the tray.\");"
window.__LT_RC_SRC+="\n    }\n  }\n\n  function bindDrag(root) {\n    var armed = null"
window.__LT_RC_SRC+=";\n    var ghost = null;\n    var capturing = null;\n\n    funct"
window.__LT_RC_SRC+="ion clearGhost() {\n      if (ghost) ghost.style.display = \"n"
window.__LT_RC_SRC+="one\";\n      document.documentElement.classList.remove(\"rc-dr"
window.__LT_RC_SRC+="agging\");\n    }\n\n    function showGhost(srcEl, x, y) {\n     "
window.__LT_RC_SRC+=" ghost = ensureGhost();\n      var img = ghost.querySelector("
window.__LT_RC_SRC+="\"img\");\n      var from = srcEl && srcEl.querySelector(\"img\")"
window.__LT_RC_SRC+=";\n      if (img) {\n        if (from && from.src) img.src = f"
window.__LT_RC_SRC+="rom.src;\n        else img.removeAttribute(\"src\");\n      }\n  "
window.__LT_RC_SRC+="    ghost.style.display = \"flex\";\n      ghost.style.left = x"
window.__LT_RC_SRC+=" - 32 + \"px\";\n      ghost.style.top = y - 32 + \"px\";\n      d"
window.__LT_RC_SRC+="ocument.documentElement.classList.add(\"rc-dragging\");\n    }\n"
window.__LT_RC_SRC+="\n    root.addEventListener(\"dragstart\", function (ev) {\n    "
window.__LT_RC_SRC+="  var t = ev.target.closest(\"[data-rc-part], [data-rc-hose]\""
window.__LT_RC_SRC+=");\n      if (!t || !ev.dataTransfer) return;\n      var part "
window.__LT_RC_SRC+="= t.getAttribute(\"data-rc-part\");\n      var hose = t.getAttr"
window.__LT_RC_SRC+="ibute(\"data-rc-hose\");\n      drag = part ? { kind: \"part\", i"
window.__LT_RC_SRC+="d: part } : { kind: \"hose\", id: hose };\n      armed = null;\n"
window.__LT_RC_SRC+="      try {\n        ev.dataTransfer.setData(\"" ,