window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="ter;justify-content:center;overflow:hidden\";\n    g.innerHTML"
window.__LT_RC_SRC+=" = '<img alt=\"\" style=\"width:52px;height:52px;object-fit:con"
window.__LT_RC_SRC+="tain;background:#efe6d6;border-radius:8px\" />';\n    document"
window.__LT_RC_SRC+=".body.appendChild(g);\n    return g;\n  }\n\n  function hitDrop("
window.__LT_RC_SRC+="x, y) {\n    var stack = [];\n    try {\n      stack = document"
window.__LT_RC_SRC+=".elementsFromPoint(x, y) || [];\n    } catch (e) {\n      var "
window.__LT_RC_SRC+="one = document.elementFromPoint(x, y);\n      if (one) stack "
window.__LT_RC_SRC+="= [one];\n    }\n    var port = null, zone = null, scale = nul"
window.__LT_RC_SRC+="l, unit = null;\n    for (var i = 0; i < stack.length; i++) {"
window.__LT_RC_SRC+="\n      var el = stack[i];\n      if (!el || !el.closest) cont"
window.__LT_RC_SRC+="inue;\n      if (!port) {\n        var p = el.closest(\"[data-r"
window.__LT_RC_SRC+="c-port]\");\n        if (p) port = p;\n      }\n      if (!scale"
window.__LT_RC_SRC+=") {\n        var sc = el.closest(\"[data-hook='scale'], #rc-sc"
window.__LT_RC_SRC+="ale-read, .rc-scale\");\n        if (sc) scale = sc;\n      }\n "
window.__LT_RC_SRC+="     if (!unit) {\n        var u = el.closest(\".rc-unit, #rc-"
window.__LT_RC_SRC+="unit-stage, .rc-unit-stage\");\n        if (u) unit = u;\n     "
window.__LT_RC_SRC+=" }\n      if (!zone) {\n        var z = el.closest(\"[data-rc-d"
window.__LT_RC_SRC+="rop]\");\n        if (z) zone = z;\n      }\n    }\n    if (!port"
window.__LT_RC_SRC+=") {\n      var pad = 8;\n      var ports = document.querySelec"
window.__LT_RC_SRC+="torAll(\"[data-rc-port]\");\n      var best = null, bestD = 1e9"
window.__LT_RC_SRC+=";\n      for (var j = 0; j < ports.length; j++) {\n        var"
window.__LT_RC_SRC+=" r = ports[j].getBoundingClientRect();\n        if (x >= r.le"
window.__LT_RC_SRC+="ft - pad && x <= r.right + pad && y >= r.top - pad && y <= r"
window.__LT_RC_SRC+=".bottom + pad) {\n          var cx = r.left + "
