window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="say.textContent = state.finishedOnce\n        ? \"Professor HU"
window.__LT_RC_SRC+="B: Nice pull. Scale was the proof. Play free — or walk it ag"
window.__LT_RC_SRC+="ain.\"\n        : \"Professor HUB: Free play. Scale is the proo"
window.__LT_RC_SRC+="f. 80% WC is a stop.\";\n      if (walk) walk.hidden = false;\n"
window.__LT_RC_SRC+="      return;\n    }\n    box.classList.remove(\"rc-guide-done\""
window.__LT_RC_SRC+=");\n    if (walk) walk.hidden = true;\n    var g = GUIDE[Math."
window.__LT_RC_SRC+="min(guideStep, GUIDE.length - 1)];\n    say.textContent = g.s"
window.__LT_RC_SRC+="ay;\n    try {\n      document.querySelectorAll(g.highlight).f"
window.__LT_RC_SRC+="orEach(function (n) {\n        n.classList.add(\"rc-hl\");\n    "
window.__LT_RC_SRC+="  });\n    } catch (e) {}\n  }\n\n  function drawNeedle(cv, psi,"
window.__LT_RC_SRC+=" max, color, label) {\n    if (!cv) return;\n    var ctx = cv."
window.__LT_RC_SRC+="getContext(\"2d\");\n    if (!ctx) return;\n    var w = cv.width"
window.__LT_RC_SRC+=", h = cv.height, cx = w / 2, cy = h / 2 + 4, r = Math.min(w,"
window.__LT_RC_SRC+=" h) * 0.38;\n    ctx.clearRect(0, 0, w, h);\n    ctx.fillStyle"
window.__LT_RC_SRC+=" = \"#0f0d0a\";\n    ctx.beginPath();\n    ctx.arc(cx, cy, r + 1"
window.__LT_RC_SRC+="0, 0, Math.PI * 2);\n    ctx.fill();\n    ctx.strokeStyle = co"
window.__LT_RC_SRC+="lor;\n    ctx.lineWidth = 2;\n    ctx.beginPath();\n    ctx.arc"
window.__LT_RC_SRC+="(cx, cy, r, Math.PI * 0.75, Math.PI * 2.25);\n    ctx.stroke("
window.__LT_RC_SRC+=");\n    var start = Math.PI * 0.75, sweep = Math.PI * 1.5;\n  "
window.__LT_RC_SRC+="  var t = Math.max(0, Math.min(1, (psi || 0) / max));\n    va"
window.__LT_RC_SRC+="r a = start + t * sweep;\n    ctx.strokeStyle = \"#f4e7c8\";\n  "
window.__LT_RC_SRC+="  ctx.lineWidth = 2.5;\n    ctx.beginPath();\n    ctx.moveTo(c"
window.__LT_RC_SRC+="x, cy);\n    ctx.lineTo(cx + Math.cos(a) * (r - 6), cy + Math"
window.__LT_RC_SRC+=".sin(a) * (r - 6));\n    ctx.stroke();\n    ctx"
