window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="(\"rc-port-blue\", true);\n      if (state.vaporHose) lo.innerH"
window.__LT_RC_SRC+="TML = '<img src=\"' + hoseDataUri(\"#2563eb\", \"LO\") + '\" alt=\""
window.__LT_RC_SRC+="\" draggable=\"false\" /><span>LO · hooked</span>';\n      else "
window.__LT_RC_SRC+="lo.innerHTML = \"<span>LO port</span>\";\n    }\n    if (hi) {\n "
window.__LT_RC_SRC+="     hi.classList.toggle(\"rc-port-red\", true);\n      if (sta"
window.__LT_RC_SRC+="te.liquidHose) hi.innerHTML = '<img src=\"' + hoseDataUri(\"#e"
window.__LT_RC_SRC+="f4444\", \"HI\") + '\" alt=\"\" draggable=\"false\" /><span>HI · hoo"
window.__LT_RC_SRC+="ked</span>';\n      else hi.innerHTML = \"<span>HI port</span>"
window.__LT_RC_SRC+="\";\n    }\n    paintMicron();\n\n    var msw = document.getEleme"
window.__LT_RC_SRC+="ntById(\"rc-machine-sw\");\n    var vsw = document.getElementBy"
window.__LT_RC_SRC+="Id(\"rc-vacuum-sw\");\n    if (msw) {\n      msw.disabled = stat"
window.__LT_RC_SRC+="e.machine !== \"bay\";\n      msw.textContent = state.machineOn"
window.__LT_RC_SRC+=" ? \"Recovery machine · ON\" : \"Recovery machine · OFF\";\n     "
window.__LT_RC_SRC+=" msw.classList.toggle(\"primary\", state.machineOn);\n    }\n   "
window.__LT_RC_SRC+=" if (vsw) {\n      vsw.disabled = state.vacuum !== \"bay\";\n   "
window.__LT_RC_SRC+="   vsw.textContent = state.vacuumOn ? \"Vacuum pump · ON\" : \""
window.__LT_RC_SRC+="Vacuum pump · OFF\";\n      vsw.classList.toggle(\"primary\", st"
window.__LT_RC_SRC+="ate.vacuumOn);\n    }\n    paintGuide();\n  }\n\n  function shopW"
window.__LT_RC_SRC+="hy(msg) {\n    setStatus(msg, true);\n  }\n\n  function narrate("
window.__LT_RC_SRC+=") {\n    advanceGuide();\n    if (atStop() && state.machine =="
window.__LT_RC_SRC+="= \"bay\") {\n      setStatus(\"80% WC — STOP. Scale is the proo"
window.__LT_RC_SRC+="f. Change cylinders. Drag the machine back to the tray.\", tr"
window.__LT_RC_SRC+="ue);\n      return;\n    }\n    if (atStop() && state.machine ="
window.__LT_RC_SRC+="== \"tray\") {\n      setStatus(\"Machine back in"
