window.__LT_RC_SRC=(window.__LT_RC_SRC||"");
window.__LT_RC_SRC+="tion setStatus(msg, warn) {\n    var s = document.getElementB"
window.__LT_RC_SRC+="yId(\"rc-status\");\n    if (!s) return;\n    s.textContent = ms"
window.__LT_RC_SRC+="g;\n    s.style.color = warn ? \"#fbbf24\" : \"#e2e8f0\";\n  }\n\n  "
window.__LT_RC_SRC+="function guideNeedMet(need) {\n    if (need === \"machineBay\")"
window.__LT_RC_SRC+=" return state.machine === \"bay\";\n    if (need === \"tankOnSca"
window.__LT_RC_SRC+="le\") return state.tank === \"bay\" && state.scale === \"bay\";\n "
window.__LT_RC_SRC+="   if (need === \"hosesLanded\") return state.vaporHose && sta"
window.__LT_RC_SRC+="te.liquidHose;\n    if (need === \"machineRunning\") return sta"
window.__LT_RC_SRC+="te.machineOn || state.recovered > 0.05 || atStop();\n    if ("
window.__LT_RC_SRC+="need === \"hitStop\") return atStop();\n    if (need === \"machi"
window.__LT_RC_SRC+="neBack\") return atStop() && state.machine === \"tray\";\n    re"
window.__LT_RC_SRC+="turn false;\n  }\n\n  function advanceGuide() {\n    if (!guideO"
window.__LT_RC_SRC+="n) return;\n    while (guideStep < GUIDE.length && guideNeedM"
window.__LT_RC_SRC+="et(GUIDE[guideStep].need)) {\n      guideStep += 1;\n    }\n   "
window.__LT_RC_SRC+=" if (guideStep >= GUIDE.length) {\n      state.finishedOnce ="
window.__LT_RC_SRC+=" true;\n      try {\n        localStorage.setItem(GUIDE_KEY, \""
window.__LT_RC_SRC+="1\");\n      } catch (e) {}\n      guideOn = false;\n    }\n    p"
window.__LT_RC_SRC+="aintGuide();\n  }\n\n  function paintGuide() {\n    var box = do"
window.__LT_RC_SRC+="cument.getElementById(\"rc-guide\");\n    var say = document.ge"
window.__LT_RC_SRC+="tElementById(\"rc-guide-say\");\n    var walk = document.getEle"
window.__LT_RC_SRC+="mentById(\"rc-walk\");\n    if (!box || !say) return;\n    docum"
window.__LT_RC_SRC+="ent.querySelectorAll(\".rc-hl\").forEach(function (n) {\n      "
window.__LT_RC_SRC+="n.classList.remove(\"rc-hl\");\n    });\n    if (!guideOn) {\n   "
window.__LT_RC_SRC+="   box.classList.add(\"rc-guide-done\");\n      "
