/* HVAC Allstars — offline cache for Android / Windows PWA */
const VER = "lt-allstars-v377";
const CORE = [
  "./",
  "./index.html",
  "./sku.js?v=14",
  "./style.css?v=146",
  "./sandbox-layout.css?v=15",
  "./phone-floor.css?v=28",
  "./phone-rail.css?v=1",
  "./saturday-phone.css?v=1",
  "./sb-tabs.css?v=3",
  "./lab-glass.css?v=1",
  "./game.js?v=206",
  "./shop-floor-copy.js?v=17",
  "./sandbox.js?v=161",
  "./sandbox-hunt.js?v=2",
  "./sandbox-eq.js?v=1",
  "./sandbox-hook.js?v=18",
  "./sandbox-seats.js?v=1",
  "./sandbox-yell.js?v=1",
  "./sandbox-ts.js?v=7",
  "./sandbox-sliders.js?v=6",
  "./sandbox-stand.js?v=1",
  "./sandbox-cutout.js?v=1",
  "./sandbox-td.js?v=4",
  "./route-floor.js?v=9",
  "./route-boot-fix.js?v=1",
  "./charge-floor.js?v=3",
  "./quiz-arena.js?v=4",
  "./quiz-arena.p0.js?v=4",
  "./quiz-arena.p1.js?v=4",
  "./quiz-arena.p2.js?v=4",
  "./quiz-arena.p3.js?v=4",
  "./quiz-arena.p4.js?v=4",
  "./quiz-arena.p5.js?v=4",
  "./quiz-arena.p6.js?v=4",
  "./quiz-arena.p7.js?v=4",
  "./quiz-arena.p8.js?v=4",
  "./quiz-arena.p9.js?v=4",
  "./quiz-arena.p10.js?v=4",
  "./quiz-arena.p11.js?v=4",
  "./quiz-arena.p12.js?v=4",
  "./quiz-arena.p13.js?v=4",
  "./quiz-arena.p14.js?v=4",
  "./quiz-arena.p15.js?v=4",
  "./hub-ai.js?v=84",
  "./drip.js?v=3",
  "./instructor.js?v=97",
  "./electrical.js?v=136",
  "./electrical-fat.js?v=4",
  "./electrical-lite.js?v=8",
  "./electrical-phone.js?v=5",
  "./electrical-sheet.js?v=2",
  "./board-codes.js?v=16",
  "./prove-deepen.js?v=2",
  "./soo-limit.js?v=1",
  "./furnace-soo-floor.js?v=1",
  "./voltmeter-school.js?v=4",
  "./ohm-school.js?v=1",
  "./ohms-law-school.js?v=4",
  "./ohms-law-arcade-bench.js?v=2",
  "./ohms-law-arcade-tickets.js?v=2",
  "./ohms-law-arcade-play.js?v=5",
  "./truck-pouch.js?v=6",
  "./truck-pouch.p0.js?v=6",
  "./truck-pouch.p1.js?v=6",
  "./truck-pouch.p2.js?v=6",
  "./truck-pouch.p3.js?v=6",
  "./truck-pouch.p4.js?v=6",
  "./truck-pouch.p5.js?v=6",
  "./truck-pouch.p6.js?v=6",
  "./truck-pouch.p7.js?v=6",
  "./truck-pouch.css?v=8",
  "./exam-untimed.js?v=3",
  "./exam-cutout.js?v=1",
  "./board-codes.css?v=4",
  "./dragdrop.js?v=49",
  "./webgl-cycle.js?v=57",
  "./minisplit.js?v=10",
  "./minisplit-phone.js?v=4",
  "./minisplit-chip-preview.js?v=1",
  "./ai-helper.js",
  "./service.js?v=108",
  "./commandments.js?v=119",
  "./epa608.js?v=2",
  "./compete.js?v=94",
  "./chat.js?v=106",
  "./badges.js?v=96",
  "./curriculum.js",
  "./daily.js?v=3",
  "./daily-clock.js?v=1",
  "./clock-in-form.js?v=21",
  "./clock-in-fix.js?v=23",
  "./clock-in-floor.js?v=43",
  "./shop-labs-data.js?v=3",
  "./shop-labs-floor.js?v=5",
  "./shop-labs-print.js?v=1"
];
self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(VER).then(function (c) { return c.addAll(CORE); }).then(function () { return self.skipWaiting(); }));
});
self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k !== VER; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});
self.addEventListener("fetch", function (e) {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request).then(function (hit) {
    return hit || fetch(e.request);
  }));
});
